### ISSUE TITLE
Resolución dell segundo conflicto

### ISSUE THREAD

**Issue by crismarort** [VeronicaMoise/Git_DGP_VM#1]
Buenas tardes Verónica,

me pongo en contacto contigo para poner en común las ideas acerca del conflicto que hemos tenido en el ejercicio1_CM.

Con respecto a la primera definición mi propuesta es que le restemos al acumulador x en lugar de sumarle su cuadrado, debido a que es una operación computacionalmente más básica.

Con respecto a la segunda definición te propongo quitarle todas las restricciones a la función.

En relación a la tercera definición, me disculpo por añadir un espacio de manera involuntaria y con ello generar un conflicto para el programa, que finalmente hemos resuelto. 

Y por último, en la definición de producto de una lista por un número mi propuesta es multiplicar el cuadrado del número dado en la definición por la lista dada.

Espero que podamos resolver dichos conflictos.
Gracias por tu tiempo.

Un saludo,
Cristina.

**Comment by VeronicaMoise** [comment]
Buenas tardes Cristina,

Gracias de antemano por tu dedicación a este archivo. 

Me gustaría comentarte que no estoy  completamente de acuerdo contigo en la segunda definición debido a que veo necesario la imposición de condiciones sobre la definición por comprensión.  De todas formas lo dejo a tu criterio de elección. Por ello, me gustaría comentarte que acepto pull requests.

Con todo lo demás estoy absolutamente de acuerdo.

Saludos.
